version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - SECRET_KEY=change_me_in_production
      - DATABASE_URL=sqlite:///pos_prod.db
    volumes:
      - ./pos_prod.db:/app/pos_prod.db
    restart: always

  # Descomentar si se usa una base de datos PostgreSQL
  # db:
  #   image: postgres:13
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=pos_db
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: always

# volumes:
#   postgres_data:
